name: Windows tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
        matrix:
          os: [windows-latest]
          go-version: ['1.24.x']

    steps:
        - name: Checkout Code
          uses: actions/checkout@v4
    
        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: ${{ matrix.go-version }}
    
        - name: Install libusb via mingw
          uses: msys2/setup-msys2@v2
          with:
            install: |-
              mingw64/mingw-w64-x86_64-libusb
              mingw64/mingw-w64-x86_64-pkg-config

        - name: Install other dependencies
          run: |
            choco install openssl.light -y
            choco install make -y
            choco install 7zip -y
            choco install zadig -y
            curl -L "https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip" -o "C:\wpcap-sdk.zip"
            7z x -y "C:\wpcap-sdk.zip" -o"C:\winpcap"
                       
        - run: echo "D:\a\_temp\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

        - name: Run Tests
          run: env GO111MODULE=on make test
        